/**
 * Mink SDK Error Codes
 * @module errors/codes
 */

/**
 * All possible error codes
 */
export const ErrorCodes = {
  // Wallet errors
  WALLET_NOT_CONNECTED: 'WALLET_NOT_CONNECTED',
  WALLET_NO_SIGN_MESSAGE: 'WALLET_NO_SIGN_MESSAGE',
  WALLET_NO_SIGN_TRANSACTION: 'WALLET_NO_SIGN_TRANSACTION',
  WALLET_SIGNATURE_REJECTED: 'WALLET_SIGNATURE_REJECTED',

  // Initialization errors
  SDK_NOT_INITIALIZED: 'SDK_NOT_INITIALIZED',
  WASM_INIT_FAILED: 'WASM_INIT_FAILED',
  KEY_DERIVATION_FAILED: 'KEY_DERIVATION_FAILED',

  // Encryption errors
  ENCRYPTION_KEY_NOT_SET: 'ENCRYPTION_KEY_NOT_SET',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',
  INVALID_ENCRYPTION_VERSION: 'INVALID_ENCRYPTION_VERSION',

  // Proof errors
  PROOF_GENERATION_FAILED: 'PROOF_GENERATION_FAILED',
  PROOF_VERIFICATION_FAILED: 'PROOF_VERIFICATION_FAILED',
  CIRCUIT_LOAD_FAILED: 'CIRCUIT_LOAD_FAILED',

  // Network errors
  RELAYER_UNREACHABLE: 'RELAYER_UNREACHABLE',
  RELAYER_ERROR: 'RELAYER_ERROR',
  RPC_ERROR: 'RPC_ERROR',

  // Transaction errors
  SIMULATION_FAILED: 'SIMULATION_FAILED',
  CONFIRMATION_TIMEOUT: 'CONFIRMATION_TIMEOUT',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  UNKNOWN_ROOT: 'UNKNOWN_ROOT',

  // Balance errors
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  NO_UTXOS: 'NO_UTXOS',
  DEPOSIT_LIMIT_EXCEEDED: 'DEPOSIT_LIMIT_EXCEEDED',

  // Validation errors
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // Inbox errors
  INBOX_NOT_FOUND: 'INBOX_NOT_FOUND',
  INBOX_NO_BALANCE: 'INBOX_NO_BALANCE',

  // General
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
